kind: AzureContainerApp
apiVersion: aca.xenit.io/v1alpha2
metadata:
  name: example-app1
spec:
  remoteSecrets:
    - secretName: foo
      remoteSecretName: foo
    - secretName: bar
      remoteSecretName: bar
  app:
    properties:
      configuration:
        activeRevisionsMode: Single
      template:
        containers:
          - name: simple-hello-world-container
            image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
            env:
              - name: FOO
                secretRef: foo
              - name: BAR
                secretRef: bar
            resources:
              cpu: 0.25
              memory: .5Gi
        scale:
          minReplicas: 1
          maxReplicas: 1
