kind: AzureContainerApp
apiVersion: aca.xenit.io/v1alpha2
metadata:
  name: example-app2
spec:
  app:
    properties:
      configuration:
        activeRevisionsMode: Single
      template:
        containers:
          - name: simple-hello-world-container
            image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
            resources:
              cpu: 0.25
              memory: .5Gi
        scale:
          minReplicas: 1
          maxReplicas: 1
