kind: AzureContainerApp
apiVersion: aca.xenit.io/v1alpha1
metadata:
  name: foobar1
spec:
  remoteSecrets:
    - appSecretName: connection-string
      remoteSecretName: mssql-connection-string
  app:
    properties:
      configuration:
        activeRevisionsMode: Single
      template:
        containers:
        - name: simple-hello-world-container
          image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
          resources:
            cpu: 0.25
            memory: .5Gi
          env:
            - name: CONNECTION_STRING
              secretRef: connection-string
            - name: MEANING_WITH_LIFE
              value: "forty two"
        scale:
          minReplicas: 1
          maxReplicas: 1
---
kind: AzureContainerApp
apiVersion: aca.xenit.io/v1alpha1
metadata:
  name: foo2
spec:
  app:
    properties:
      configuration:
        activeRevisionsMode: Single
      template:
        containers:
        - name: simple-hello-world-container
          image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
          resources:
            cpu: 0.25
            memory: .5Gi
        scale:
          minReplicas: 1
          maxReplicas: 1