kind: AzureContainerJob
apiVersion: aca.xenit.io/v1alpha2
metadata:
  name: example-job1
spec:
  remoteSecrets:
    - secretName: foo
      remoteSecretName: foo
    - secretName: baz
      remoteSecretName: baz
  job:
    properties:
      configuration:
        scheduleTriggerConfig:
          cronExpression: "*/5 * * * *"
          parallelism: 1
          replicaCompletionCount: 1
        replicaRetryLimit: 1
        replicaTimeout: 1800
        triggerType: Schedule
      template:
        containers:
          - name: simple-hello-world-container
            image: mcr.microsoft.com/k8se/quickstart-jobs:latest
            env:
              - name: FOO
                secretRef: foo
              - name: BAZ
                secretRef: baz
            resources:
              cpu: 0.25
              memory: .5Gi
